sudo: required
dist: trusty
group: edge
language: php
php:
- '7.0'
- nightly
- hhvm
- '5.6'

addons:
  apt:
    packages:
    - python3
before_script:
- composer update --dev
script:
- "tests/testing.php"
before_install:
- openssl aes-256-cbc -K $encrypted_0b05103af24b_key -iv $encrypted_0b05103af24b_iv
  -in enc.tar.xz.enc -out enc.tar.xz -d
- tar -xJpf enc.tar.xz
